/*

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"time"

	v1alpha1 "github.com/oam-dev/cloud-provider/alibabacloud/ros/apis/ros.alibabacloud.com/v1alpha1"
	scheme "github.com/oam-dev/cloud-provider/alibabacloud/ros/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// RosStacksGetter has a method to return a RosStackInterface.
// A group's client should implement this interface.
type RosStacksGetter interface {
	RosStacks(namespace string) RosStackInterface
}

// RosStackInterface has methods to work with RosStack resources.
type RosStackInterface interface {
	Create(*v1alpha1.RosStack) (*v1alpha1.RosStack, error)
	Update(*v1alpha1.RosStack) (*v1alpha1.RosStack, error)
	UpdateStatus(*v1alpha1.RosStack) (*v1alpha1.RosStack, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.RosStack, error)
	List(opts v1.ListOptions) (*v1alpha1.RosStackList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.RosStack, err error)
	RosStackExpansion
}

// rosStacks implements RosStackInterface
type rosStacks struct {
	client rest.Interface
	ns     string
}

// newRosStacks returns a RosStacks
func newRosStacks(c *RosV1alpha1Client, namespace string) *rosStacks {
	return &rosStacks{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the rosStack, and returns the corresponding rosStack object, and an error if there is any.
func (c *rosStacks) Get(name string, options v1.GetOptions) (result *v1alpha1.RosStack, err error) {
	result = &v1alpha1.RosStack{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("rosstacks").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of RosStacks that match those selectors.
func (c *rosStacks) List(opts v1.ListOptions) (result *v1alpha1.RosStackList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.RosStackList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("rosstacks").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested rosStacks.
func (c *rosStacks) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("rosstacks").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a rosStack and creates it.  Returns the server's representation of the rosStack, and an error, if there is any.
func (c *rosStacks) Create(rosStack *v1alpha1.RosStack) (result *v1alpha1.RosStack, err error) {
	result = &v1alpha1.RosStack{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("rosstacks").
		Body(rosStack).
		Do().
		Into(result)
	return
}

// Update takes the representation of a rosStack and updates it. Returns the server's representation of the rosStack, and an error, if there is any.
func (c *rosStacks) Update(rosStack *v1alpha1.RosStack) (result *v1alpha1.RosStack, err error) {
	result = &v1alpha1.RosStack{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("rosstacks").
		Name(rosStack.Name).
		Body(rosStack).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *rosStacks) UpdateStatus(rosStack *v1alpha1.RosStack) (result *v1alpha1.RosStack, err error) {
	result = &v1alpha1.RosStack{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("rosstacks").
		Name(rosStack.Name).
		SubResource("status").
		Body(rosStack).
		Do().
		Into(result)
	return
}

// Delete takes name of the rosStack and deletes it. Returns an error if one occurs.
func (c *rosStacks) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("rosstacks").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *rosStacks) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("rosstacks").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched rosStack.
func (c *rosStacks) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.RosStack, err error) {
	result = &v1alpha1.RosStack{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("rosstacks").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
