/*

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/oam-dev/cloud-provider/alibabacloud/ros/apis/ros.alibabacloud.com/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeRosStacks implements RosStackInterface
type FakeRosStacks struct {
	Fake *FakeRosV1alpha1
	ns   string
}

var rosstacksResource = schema.GroupVersionResource{Group: "ros.alibabacloud.com", Version: "v1alpha1", Resource: "rosstacks"}

var rosstacksKind = schema.GroupVersionKind{Group: "ros.alibabacloud.com", Version: "v1alpha1", Kind: "RosStack"}

// Get takes name of the rosStack, and returns the corresponding rosStack object, and an error if there is any.
func (c *FakeRosStacks) Get(name string, options v1.GetOptions) (result *v1alpha1.RosStack, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(rosstacksResource, c.ns, name), &v1alpha1.RosStack{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.RosStack), err
}

// List takes label and field selectors, and returns the list of RosStacks that match those selectors.
func (c *FakeRosStacks) List(opts v1.ListOptions) (result *v1alpha1.RosStackList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(rosstacksResource, rosstacksKind, c.ns, opts), &v1alpha1.RosStackList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.RosStackList{ListMeta: obj.(*v1alpha1.RosStackList).ListMeta}
	for _, item := range obj.(*v1alpha1.RosStackList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested rosStacks.
func (c *FakeRosStacks) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(rosstacksResource, c.ns, opts))

}

// Create takes the representation of a rosStack and creates it.  Returns the server's representation of the rosStack, and an error, if there is any.
func (c *FakeRosStacks) Create(rosStack *v1alpha1.RosStack) (result *v1alpha1.RosStack, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(rosstacksResource, c.ns, rosStack), &v1alpha1.RosStack{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.RosStack), err
}

// Update takes the representation of a rosStack and updates it. Returns the server's representation of the rosStack, and an error, if there is any.
func (c *FakeRosStacks) Update(rosStack *v1alpha1.RosStack) (result *v1alpha1.RosStack, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(rosstacksResource, c.ns, rosStack), &v1alpha1.RosStack{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.RosStack), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeRosStacks) UpdateStatus(rosStack *v1alpha1.RosStack) (*v1alpha1.RosStack, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(rosstacksResource, "status", c.ns, rosStack), &v1alpha1.RosStack{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.RosStack), err
}

// Delete takes name of the rosStack and deletes it. Returns an error if one occurs.
func (c *FakeRosStacks) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(rosstacksResource, c.ns, name), &v1alpha1.RosStack{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeRosStacks) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(rosstacksResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.RosStackList{})
	return err
}

// Patch applies the patch and returns the patched rosStack.
func (c *FakeRosStacks) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.RosStack, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(rosstacksResource, c.ns, name, pt, data, subresources...), &v1alpha1.RosStack{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.RosStack), err
}
